### ISSUE TITLE
Anmerkungen zum Dockerfile

### ISSUE THREAD

**Issue by ptweety** [ThetaGamma/ccu-jack#2]
Hi @ThetaGamma,

ich würde gerne ein paar Vorschläge zum Dockerfile zur Diskussion stellen.

- von GitHub die Version der letzten stabilen Version holen
- die Config beschreibbar machen (sonst kann kein Nutzer über das UI angelegt werden)
- Informationen zum BUILD einfügen
- LABELs hinzufügen
- Statt root den Container als normaler Nutzer betreiben
- Ein HEALTCHECK hinzugefügt

Ich hoffe, es hilft ein wenig.

Edit: HEALTHCHECK geändert

```
# 1. build the image with
#   export BUILD_VERSION=$(curl -Ls https://api.github.com/repos/mdzio/ccu-jack/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')
#   docker build --rm --no-cache \
#    --build-arg BUILD_VERSION="${BUILD_VERSION}" \
#    --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
#    --tag ccu-jack:latest .
#
# 2. mount your config into container and run the image, i.e.
#   docker run --rm -v "$PWD"/ccu-jack.cfg:/go/src/app/ccu-jack.cfg ccu-jack:latest

FROM golang:alpine

ARG BUILD_DATE
ARG BUILD_VERSION

LABEL org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.version=$BUILD_VERSION \
      org.opencontainers.image.title="CCU-Jack" \
      org.opencontainers.image.description="REST/MQTT-Server for the HomeMatic CCU" \
      org.opencontainers.image.vendor="CCU-Jack OpenSource Project" \
      org.opencontainers.image.authors="mdzio <info@ccu-historian.de>" \
      org.opencontainers.image.licenses="GPL-3.0 License" \
      org.opencontainers.image.url="https://github.com/mdzio/ccu-jack" \
      org.opencontainers.image.documentation="https://github.com/mdzio/ccu-jack/blob/master/README.md"

# Set work directory
WORKDIR /go/src/app

# Get the latest relase from github and extract it locally
RUN apk add --no-cache curl && \
    curl -SL "https://github.com/mdzio/ccu-jack/releases/download/v${BUILD_VERSION}/ccu-jack-linux-${BUILD_VERSION}.tar.gz" | tar -xvzC . && \
    mkdir -p /go/src/app /data && \
    adduser -h /go/src/app -D -H ccu-jack -u 1000 && \
    chown -R ccu-jack:root /data && chmod -R g+rwX /data && \
    chown -R ccu-jack:root /go/src/app && chmod -R g+rwX /go/src/app

USER ccu-jack

# MQTT, MQTT TLS, CCU-Jack VEAM/UI, CCU-Jack VEAM/UI TLS
EXPOSE 1883 8883 2121 2122

# Add a healthcheck (default every 30 secs)
HEALTHCHECK CMD curl -s -o /dev/null -il -w "%{http_code}\n" http://localhost:2121 | grep -Eq "(200|401)" || exit 1

# start it up
CMD ["./ccu-jack"]
```

**Comment by ptweety** [comment]
Und da fällt mir beim nochmaligen Test auf, dass der HEALTHCHECK in die Grütze geht, sobald man einen Nutzer über das UI anlegt. Vorher bekommt man einen sauberen HTTP 200 zurück und dann halt einen 401 wegen mangelnder Berechtigung. Hmmmm ... EDIT: fixed

**Comment by ThetaGamma** [comment]
Hallo @ptweety 
finde ich sehr gut! Ich überlege, ob es sinnvoll wäre zwei Dockerfiles zu nehmen. Ein einfaches in der Art wie es jetzt existiert (plus deine Ergänzungen), wo man einfach nur den aktuellen Release drin entpackt (sozusagen als "stable") und ein "nightly", wo man wie in deinem Beispiel den aktuellen Code compiliert. Den "stable" könnte man dann auf Docker-Hub veröffentlichen, so dass es für den ganz unbedarften Nutzer noch einfacher wird.
EDIT und mein commit fixt natürlich nicht dieses Issue, sondern issue #1 und ich hab keine Ahnung, wie ich das wieder weg bekomme *sight*

**Comment by ThetaGamma** [comment]
funktioniert soweit (vgl commit im devel branch). Wenn ich allerdings den User switche, startet das programm nicht mehr, weil es nicht auf ca-certs zugreifen kann... da muss ich noch ein wenig Gehrinschmalz reinstecken...

**Comment by ptweety** [comment]
Was mir auch im Kontext von #3 eingefallen ist, es braucht das baseimage von Golang gar nicht, weil wir ja einfach das statische binary verwenden. Und um minimal zu bleiben, trotzdem aber einen HEALTHCHECK über curl machen wollen, dann wäre dies mein neuer Vorschlag:

```
docker images ccu-jack                 
REPOSITORY   TAG       IMAGE ID       CREATED          SIZE
ccu-jack     latest    4c1908b4e02a   11 minutes ago   17.1MB
```

```
# 1. build the image with
#   export BUILD_VERSION=$(curl -Ls https://api.github.com/repos/mdzio/ccu-jack/releases/latest | grep -oP '"tag_name": "v\K(.*)(?=")')
#   docker build --rm --no-cache \
#    --build-arg BUILD_VERSION="${BUILD_VERSION}" \
#    --build-arg BUILD_DATE="$(date +"%Y-%m-%dT%H:%M:%SZ")" \
#    --tag ccu-jack:latest .
#
# 2. mount your config into container and run the image, i.e.
#   docker run --rm -v ./etc/ccu-jack/ccu-jack.cfg:/app/ccu-jack.cfg ccu-jack:latest

FROM alpine

ARG BUILD_DATE
ARG BUILD_VERSION=1.0.1

LABEL org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.version=$BUILD_VERSION \
      org.opencontainers.image.title="CCU-Jack" \
      org.opencontainers.image.description="REST/MQTT-Server for the HomeMatic CCU" \
      org.opencontainers.image.vendor="CCU-Jack OpenSource Project" \
      org.opencontainers.image.authors="mdzio <info@ccu-historian.de>" \
      org.opencontainers.image.licenses="GPL-3.0 License" \
      org.opencontainers.image.url="https://github.com/mdzio/ccu-jack" \
      org.opencontainers.image.documentation="https://github.com/mdzio/ccu-jack/blob/master/README.md"

# Set work directory
WORKDIR /app

# Get the latest relase from github and extract it locally
RUN apk add --no-cache curl && \
    curl -SL "https://github.com/mdzio/ccu-jack/releases/download/v${BUILD_VERSION}/ccu-jack-linux-${BUILD_VERSION}.tar.gz" | tar -xvzC . && \
    mkdir -p /app /data && \
    adduser -h /app -D -H ccu-jack -u 1000 -s /sbin/nologin && \
    chown -R ccu-jack:root /data && chmod -R g+rwX /data && \
    chown -R ccu-jack:root /app && chmod -R g+rwX /app

USER ccu-jack

# MQTT, MQTT TLS, CCU-Jack VEAM/UI, CCU-Jack VEAM/UI TLS
EXPOSE 1883 8883 2121 2122

# Add a healthcheck (default every 30 secs)
HEALTHCHECK CMD curl -s -o /dev/null -il -w "%{http_code}\n" http://localhost:2121 | grep -Eq "(200|401)" || exit 1

# Start it up
CMD ["./ccu-jack"]
```

**Comment by ThetaGamma** [comment]
zwei * ein Gedanke ;-) Genau das selbe hab ich gerade auch versucht, nachdem das Scratch Image nicht wirklich mit deinem vorgeschlagenen User-Switch harmoniert. Und der Unterschied ist echt marginal: Scratch: 9,1 MB, Alpine: 14,7 MB. ~~Ich würde aber vorerst bei der Variante mit dem Multistage build bleiben wollen~~ (<-- EDIT macht keinen Sinn in der Konstellation)

**Comment by ptweety** [comment]
Nächster Schritt wäre dann wohl auch noch multi-arch container bereitzustellen. Aber da fehlt mir schlicht die Erfahrung und die Testumgebung.

Hier mal eine Übersicht, die als Basis herhalten kann. @mdzio, was ist deine Meinung?

Zielsystem | Dateiname | Container
-- | -- | --
CCU2 | ccu-jack-ccu2-*.tar.gz | nein
RaspberryMatic auf Raspberry Pi Zero oder 1 | ccu-jack-rm-rp0+1-*.tar.gz | nein
CCU3 oder RaspberryMatic auf Raspberry Pi 2, 3 | ccu-jack-ccu3-rm-rp2+3-*.tar.gz | nein
RaspberryMatic auf Raspberry Pi 4 | ccu-jack-rm-rp4-*.tar.gz | nein
(Virtualisierte) CCU auf x86-Basis (z.B. RM-intelnuc o. -ova) | ccu-jack-vccu-x86-*.tar.gz | benötigt?
Windows (x64) | ccu-jack-win-*.zip | ja
Linux (x64) | ccu-jack-linux-*.tar.gz | ja
Darwin/macOS (x64) | ccu-jack-darwin-*.tar.gz | ja

**Comment by ThetaGamma** [comment]
von meiner Seite sieht es gut aus, wenn das README auch verständlich ist, könnte ich es zum Hauptzweig mergen. Deine Idee @ptweety ist sicher sinnvoll, aber auch für mich nicht machbar. Das Issue schliesse ich, wenn noch jemand die aktuellen Änderungen getestet hat. Danke für die Unterstützung!

**Comment by mdzio** [comment]
Linux mit x86 (Distribution CCU auf x86-Basis) wird als Plattform wahrscheinlich nicht benötigt.
Eventuell ist noch Linux mit Arm64 sinnvoll (Distribution RaspberryMatic auf Raspberry Pi 4).

**Comment by ThetaGamma** [comment]
fix with https://github.com/ThetaGamma/ccu-jack/commit/933836d7c660bd07cf146f98b87e885651fd61d2
