### ISSUE TITLE
Minimales Docker-Image

### ISSUE THREAD

**Issue by mdzio** [ThetaGamma/ccu-jack#3]
Die ausführbare Datei vom CCU-Jack sollte auch ohne Alpine-Linux laufen. Dadurch kann das Docker-Image auf ein paar MB reduziert werden. Im Dockerfile sollte `FROM scratch` verwendet werden können. Getestet habe ich es noch nicht,

**Comment by ThetaGamma** [comment]
Funktioniert. Um die tar zu entpacken musste ich auf staged build umstellen, aber dann klappt es. Von 310MB mit golang alpine auf sensationelle 9,1MB image size.

**Comment by ThetaGamma** [comment]
solved by using alpine
